variable "instance_name" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "gold_owner" {}
variable "newrelic_liscense_key"{}
variable "ssh_user" {}
variable "ssh_key" {}
variable "preview_mongo_database" {}
variable "preview_mongo_initdb_root_username" {}
variable "preview_mongo_initdb_root_password" {}
variable "preview_mongo_initdb_database" {}
variable "preview_mongo_database_username" {}
variable "preview_mongo_database_password" {}
variable "preview_mongo_admin_url" {}
variable "preview_database_url" {}
variable "preview_okta_domain" {}
variable "preview_okta_api_key" {}
variable "preview_okta_audience" {}
variable "preview_environment" {}
