sequenceDiagram
%% @config(../.vscode/settings.json)
  participant W as Web App
  participant O as Okta
  W->>O: Authenticate
  Note over W,O: oktaClient.signIn({ username, password })
  O-->>W: Return Transaction
  Note over W,O: Response with authentication status
  alt status == LOCKED_OUT
    Note left of W: User is redirected to account locked page
  else status == MFA_ENROLL
    W->>O: Request list of second factor options
    O-->>W: List of second factor options
      Note left of W: User selects second factor option
      alt Factor Type == Call or SMS
        Note left of W: User selects Call or SMS
        W->>O: Enroll MFA with Phone number
        Note over W,O: factor.enroll({<br/>profile: { phoneNumber, updatePhone: true }<br/>})
      else Factor Type == Email or Software Token
        Note left of W: User selects other factor
        W->>O: Enroll MFA
        Note over W,O: factor.enroll({})
      end
    O-->>W: Return one-time password (OTP)
    Note left of W: User enters OTP
    W->>O: Verify MFA
    O-->>W: Response with authentication status SUCCESS
    Note left of W: Continue to status == SUCCESS
  else status == MFA_REQUIRED
    Note left of W: User enters OTP
    W->>O: Verify MFA
    Note over W,O: transaction.verify({ passCode: otp, autoPush: true })
    O-->>W: Response with authentication status SUCCESS
    Note left of W: Continue to status == SUCCESS
  else status == SUCCESS
    W->>O: Request access token
    Note over W,O: oktaClient.token.getWithoutPrompt({<br/>responseType, scopes, sessionToken, state, prompt<br/>})
    O-->>W: Response with access tokens
    Note over W,O: Store tokens in the token manager<br/>oktaClient.tokenManager.setTokens(tokens)
  end
