import React from 'react';

const LoginMFAVerifyAuthApp = () => {

  return (
    <div id="start-main-content">
      <div className="ds-l-container">
        <div className="login-card login-card__auth_app">					
          <h1 className="ds-u-margin--0">Configure Multi-Factor Authentication</h1>
          <p className="ds-u-padding-bottom--2"><strong>Step 1:</strong> Please access your preferred <strong>Authenticator</strong> app through the app store on your phone.</p>
          <p><strong>Step 2:</strong> To register your device scan the <strong>QR code</strong> through the <strong>Authenticator</strong> app on your smart phone.</p>
          <div className="ds-u-display--flex ds-u-justify-content--between ds-u-margin-x--5 ds-u-align-items--center ds-u-margin-bottom--4">
            <img src="https://via.placeholder.com/200" />
            <span>OR</span>
            <div className="ds-u-display--flex ds-u-flex-direction--column ds-u-align-items--center">
              <p>Use the following secret</p>
              <p><strong>HWER ISJ2 WOEE BAQW</strong></p>
              <p>(Spaces don’t matter)</p>
            </div>
          </div>
          <p><strong>Step 3:</strong> Enter the Passcode generated by the <strong>Authenticator</strong> app.</p>
          {/*  Note: For accessibility a label is required for all inputs. 
            <label class="ds-c-label ds-u-margin-top--0" for="input-singleline">
          <span>Single line field</span>
          </label> */}
          <input
            class="ds-c-field ds-c-field--medium"
            id="input-singleline"
            name="singleline"
            value=""
            type="text"
          />
        </div>
      </div>
    </div>
  );
};

export default LoginMFAVerifyAuthApp;
